[tool.poetry]
name = "parabellum"
version = "0.1.0"
description = ""
authors = ["Guilherme Marim <3b853b@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
